import { ProfileConfig } from './types.js';

export const balancedProfile: ProfileConfig = {
  description: "Balanced set for general use (~Xk tokens, 18 tools)",
  tools: {
    think: true,
    focus: true,
    tachi: true,
    nextThought: true,
    usage_stats: true,
    perplexity_ask: true,
    perplexity_reason: true,
    perplexity_research: false,
    grok_reason: true,
    grok_code: true,
    grok_debug: false,
    grok_architect: false,
    grok_brainstorm: false,
    grok_search: true,
    openai_reason: true,
    openai_brainstorm: true,
    openai_code_review: false,
    openai_explain: false,
    gemini_brainstorm: true,
    gemini_analyze_code: true,
    gemini_analyze_text: true,
    qwen_coder: true,
    kimi_thinking: true,
    qwen_competitive: false,
    workflow: true,
    list_workflows: true,
    create_workflow: true,
    visualize_workflow: true,
    workflow_start: false,
    continue_workflow: false,
    workflow_status: false,
    validate_workflow: false,
    validate_workflow_file: false,
  }
};
