import { ProfileConfig } from './types.js';

export const codeFocusProfile: ProfileConfig = {
  description: "Code-heavy work with debugging and analysis (~Xk tokens, 15 tools)",
  tools: {
    think: true,
    focus: true,
    tachi: true,
    nextThought: true,
    usage_stats: true,
    perplexity_ask: true,
    perplexity_reason: false,
    perplexity_research: false,
    grok_reason: true,
    grok_code: true,
    grok_debug: true,
    grok_architect: false,
    grok_brainstorm: false,
    grok_search: false,
    openai_reason: false,
    openai_brainstorm: false,
    openai_code_review: true,
    openai_explain: false,
    openai_search: false,
    gemini_brainstorm: true,
    gemini_analyze_code: true,
    gemini_analyze_text: false,
    gemini_search: false,
    qwen_coder: true,
    qwen_algo: true,
    qwen_reason: false,        // Not needed for code focus
    kimi_thinking: true,
    qwen_competitive: false,
    minimax_code: true,        // Cheap SWE - perfect for code focus
    minimax_agent: false,
    workflow: true,
    list_workflows: true,
    create_workflow: false,
    visualize_workflow: false,
    workflow_start: false,
    continue_workflow: false,
    workflow_status: false,
    validate_workflow: true,
    validate_workflow_file: false,
    list_prompt_techniques: true,
    preview_prompt_technique: true,
    execute_prompt_technique: true,
  }
};
