import { ProfileConfig } from './types.js';

export const codeFocusProfile: ProfileConfig = {
  description: "Code-heavy work with debugging and analysis (~Xk tokens, 15 tools)",
  tools: {
    think: true,
    focus: true,
    nextThought: true,
    perplexity_ask: true,
    perplexity_reason: false,
    perplexity_research: false,
    grok_reason: true,
    grok_code: true,
    grok_debug: true,
    grok_architect: false,
    grok_brainstorm: false,
    grok_search: false,
    openai_gpt5_reason: false,
    openai_compare: false,
    openai_brainstorm: false,
    openai_code_review: true,
    openai_explain: false,
    gemini_brainstorm: true,
    gemini_analyze_code: true,
    gemini_analyze_text: false,
    qwen_coder: true,
    kimi_thinking: true,
    qwen_competitive: false,
    workflow: true,
    list_workflows: true,
    create_workflow: false,
    visualize_workflow: false,
    workflow_start: false,
    continue_workflow: false,
    workflow_status: false,
    validate_workflow: true,
    validate_workflow_file: false,
  }
};
