import { ProfileConfig } from './types.js';

export const fullProfile: ProfileConfig = {
  description: "All tools enabled for maximum capability (~Xk tokens, 32 tools)",
  tools: {
    think: true,
    focus: true,
    tachi: true,
    nextThought: true,
    usage_stats: true,
    perplexity_ask: true,
    perplexity_reason: true,
    perplexity_research: true,
    grok_reason: true,
    grok_code: true,
    grok_debug: true,
    grok_architect: true,
    grok_brainstorm: true,
    grok_search: true,
    openai_reason: true,
    openai_brainstorm: true,
    openai_code_review: true,
    openai_explain: true,
    openai_search: true,
    gemini_brainstorm: true,
    gemini_analyze_code: true,
    gemini_analyze_text: true,
    gemini_search: true,
    qwen_coder: true,
    qwen_algo: true,
    qwen_reason: true,
    kimi_thinking: true,
    qwen_competitive: true,
    minimax_code: true,
    minimax_agent: true,
    workflow: true,
    list_workflows: true,
    create_workflow: true,
    visualize_workflow: true,
    workflow_start: true,
    continue_workflow: true,
    workflow_status: true,
    validate_workflow: true,
    validate_workflow_file: true,
    list_prompt_techniques: true,
    preview_prompt_technique: true,
    execute_prompt_technique: true,
  }
};
