import { ProfileConfig } from './types.js';

export const minimalProfile: ProfileConfig = {
  description: "Minimal essential tools for basic tasks (~Xk tokens, 8 tools)",
  tools: {
    think: true,
    focus: true,
    tachi: true,
    nextThought: true,
    usage_stats: true,
    perplexity_ask: true,
    perplexity_reason: false,
    perplexity_research: false,
    grok_reason: true,
    grok_code: false,
    grok_debug: false,
    grok_architect: false,
    grok_brainstorm: false,
    grok_search: false,
    openai_reason: false,
    openai_brainstorm: false,
    openai_code_review: false,
    openai_explain: false,
    openai_search: false,
    gemini_brainstorm: true,
    gemini_analyze_code: false,
    gemini_analyze_text: false,
    gemini_search: false,
    qwen_coder: true,
    qwen_algo: false,
    kimi_thinking: false,
    qwen_competitive: false,
    workflow: true,
    list_workflows: false,
    create_workflow: false,
    visualize_workflow: false,
    workflow_start: false,
    continue_workflow: false,
    workflow_status: false,
    validate_workflow: false,
    validate_workflow_file: false,
    list_prompt_techniques: true,
    preview_prompt_technique: false,
    execute_prompt_technique: false,
  }
};
